name: Make 1


on:
  push:
    branches: [ main ]
    # paths:
    #   - "1/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    # paths:
    #   - "1/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ng-htec/workflows/.github/workflows/BuildAndPublishDockerImage.yml@main
      - name: Build 1
        if: ${{ github.event_name == 'push' && github.push.branches == 'main' && github.push.paths == '1/**' }}
        with:
          what_to_build: 1
        run: echo Test1
        # secrets:
        #   registry: ${{ secrets.REGISTRY }}
        #   username: ${{ secrets.REGISTRY_USERNAME }}
        #   password: ${{ secrets.REGISTRY_PASSWORD }}