name: Make 1


on:
  push:
    branches: [ main ]
    # paths:
    #   - "1/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    # paths:
    #   - "1/***"

# jobs:
#   build:
#     uses: ng-htec/workflows/.github/workflows/BuildAndPublishDockerImage.yml@main
#     if: ${{ github.paths == '1/**' }}
#     with:
#       what_to_build: 1
#     secrets:
#       registry: ${{ secrets.REGISTRY }}
#       username: ${{ secrets.REGISTRY_USERNAME }}
#       password: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:

    steps:

      - uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: 1/**

      - uses: ng-htec/workflows/.github/workflows/BuildAndPublishDockerImage.yml@main
        id: build1
        if: steps.changed-front.outputs.changed == 'true'
        with:
          what_to_build: 1
        # secrets:
        #   registry: ${{ secrets.REGISTRY }}
        #   username: ${{ secrets.REGISTRY_USERNAME }}
        #   password: ${{ secrets.REGISTRY_PASSWORD }}