name: Make 1


on:
  push:
    branches: [ main ]
    # paths:
    #   - "1/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    # paths:
    #   - "1/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build 1
        uses: ng-htec/workflows/.github/workflows/BuildAndPublishDockerImage.yml@main
        if: ${{ github.event_name == 'push' && github.push.branches == 'main' && github.push.paths == '1/**' }}
        with:
          what_to_build: 1
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}