name: Make 3

on:
  push:
    branches: [ main ]
    paths:
      - "3/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    paths:
      - "3/**"


jobs:
  build:
    uses: ng-htec/workflows/.github/workflows/BuildAndPublishDockerImage.yml@main
    with:
      what_to_build: 3
    secrets:
      registry: ${{ secrets.REGISTRY }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}